### ISSUE TITLE
Add me to Team

### ISSUE THREAD

**Issue by bennypowers** [esm-bundle/new-repo-instructions#1]
### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/oidc-client

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment]
Done - you can accept your invitation at https://github.com/esm-bundle. Welcome - let me know when you're ready for me to set up Travis CI env variables for the project and I'll do so.

**Comment by bennypowers** [comment]
thanks
