### ISSUE TITLE
Repo Access

### ISSUE THREAD

**Issue by rafabernad** [esm-bundle/new-repo-instructions#10]
### My username on npmjs.com

My username on npmjs.com is rafabernad

### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/lottie-web

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment]
Welcome - here's the repo https://github.com/esm-bundle/lottie-web
