### ISSUE TITLE
I'd like to publish an @esm-bundle package

### ISSUE THREAD

**Issue by princed** [esm-bundle/new-repo-instructions#12]
I just wanted a tool to automatically publish an ESM version of a package, but here you've got a whole ecosystem. It's an amazing effort, thank you! 

### My username on npmjs.com

My username on npmjs.com is princed

### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/mui-datatables

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment]
Welcome @princed, here's the repo: https://github.com/esm-bundle/mui-datatables. Please fork and pull request with the necessary changes. We've stopped giving write access to strangers for fear that they'd use the access to mine the github and npm tokens we use for publishing.

**Comment by princed** [comment]
That totally makes sense, thank you!
I was actually a bit worried about needing to use my token for this 😅
