### ISSUE TITLE
SystemJS syntax for Vuex

### ISSUE THREAD

**Issue by mhustonpax8** [esm-bundle/new-repo-instructions#13]
### My username on npmjs.com

My username on npmjs.com is hustonapps

### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/vuex

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment]
Done, see https://github.com/esm-bundle/vuex. Also note that I updated the instructions in the readme of this repo - we recently changed the process so that we can reuse the same github and npm tokens for all repos.
