### ISSUE TITLE
Please create an esm-bundle repos for: classnames, markdown-it, markdown-it-emoji

### ISSUE THREAD

**Issue by vitalii-kyktov** [esm-bundle/new-repo-instructions#14]
### Please create an esm-bundle repo for the following package(s):

- https://www.npmjs.com/package/classnames
- https://www.npmjs.com/package/markdown-it
- https://www.npmjs.com/package/markdown-it-emoji

**Comment by joeldenning** [comment]
Done:

https://github.com/esm-bundle/classnames
https://github.com/esm-bundle/markdown-it
https://github.com/esm-bundle/markdown-it-emoji

**Comment by internettrans** [comment]
Note that the new repos are not finished. It's up to you to pull request them with the necessary changes, as described in https://github.com/esm-bundle/new-repo-instructions#okay-how-do-i-do-it

**Comment by vitalii-kyktov** [comment]
Hello, Joel, thanks a lot. Today I will proceed with preparation of pull requests.
