### ISSUE TITLE
Add i18next & react-i18next

### ISSUE THREAD

**Issue by eljo** [esm-bundle/new-repo-instructions#16]
### Please create an esm-bundle repo for the following package(s):

- https://www.npmjs.com/package/i18next
- https://www.npmjs.com/package/react-i18next

### Steps for esm-bundle maintainer

The maintainers of esm-bundle will do the following:

1. Create a repo from this template. Click on "Use Template". The new repo must be under the `esm-bundle` repo https://github.com/esm-bundle/autopublish-template
2. Create branch protection rule for the `main` branch. Code reviews are required by a code owner before merge, and the `build` github workflow must succeed before merge.

### Steps for new contributor

Once the maintainer has created the repository, fork it and follow these steps: https://github.com/esm-bundle/new-repo-instructions#okay-how-do-i-do-it. Once finished, submit a pull request, which will be reviewed by the maintainers.

**Comment by internettrans** [comment]
Created at https://github.com/esm-bundle/i18next and https://github.com/esm-bundle/react-18next
