### ISSUE TITLE
esm-bundle/single-spa-angular

### ISSUE THREAD

**Issue by OriolInvernonLlaneza** [esm-bundle/new-repo-instructions#18]
### Please create an esm-bundle repo for the following package(s):

- https://www.npmjs.com/package/single-spa-angular

### Steps for esm-bundle maintainer

The maintainers of esm-bundle will do the following:

1. Create a repo from this template. Click on "Use Template". The new repo must be under the `esm-bundle` repo https://github.com/esm-bundle/autopublish-template
2. Create branch protection rule for the `main` branch. Code reviews are required by a code owner before merge, and the `build` github workflow must succeed before merge.

### Steps for new contributor

Once the maintainer has created the repository, fork it and follow these steps: https://github.com/esm-bundle/new-repo-instructions#okay-how-do-i-do-it. Once finished, submit a pull request, which will be reviewed by the maintainers.

**Comment by internettrans** [comment]
Rather than creating an esm-bundle workaround for this, i'd prefer fixing single-spa-angular, since I help maintain it and have write/publish access.
