### ISSUE TITLE
Grant me access to do all the things

### ISSUE THREAD

**Issue by TheMcMurder** [esm-bundle/new-repo-instructions#2]
### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/moment

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment]
Done

**Comment by joeldenning** [comment]
Go to https://github.com/esm-bundle to accept the invite
