### ISSUE TITLE
Access and a question about versions

### ISSUE THREAD

**Issue by drixsonic** [esm-bundle/new-repo-instructions#7]
### My username on npmjs.com

My username on npmjs.com is drixsonic

### I will create an esm-bundle repo for the following npm packages:
- https://github.com/mui-org/material-ui

Or at least for @material-ui/styles at first

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

---

But before creating my first repo, I have some concerns about versioning. How and when are the versions bumped? As the released URLs contain no version, a new release could potentially break a production website depending on it, if that release has a breaking change, or did I miss something?

**Comment by joeldenning** [comment]
> But before creating my first repo, I have some concerns about versioning. How and when are the versions bumped? As the released URLs contain no version, a new release could potentially break a production website depending on it, if that release has a breaking change, or did I miss something?

You can add version numbers to the URLs in the readme to pin to a specific version. For example - https://cdn.jsdelivr.net/npm/@esm-bundle/react@16.13.1/esm/react.development.js

esm-bundle uses https://github.com/esm-bundle/release-it-plugin-esm-bundle during its CI process to determine the version number to be published to NPM. See https://github.com/esm-bundle/release-it-plugin-esm-bundle/blob/8e13c900ab3083a13d3b6abd9018151513e8add9/index.js#L39 for more details.

I have given you the ability to create repositories in this github organization. You should be able to see a banner at the top inviting you at https://github.com/esm-bundle

**Comment by drixsonic** [comment]
Ok, great! Thank you for the invite 😊
