### ISSUE TITLE
Repo access request for @rajasegar

### ISSUE THREAD

**Issue by rajasegar** [esm-bundle/new-repo-instructions#9]
### My username on npmjs.com

My username on npmjs.com is rajasegar

### I will create an esm-bundle repo for the following npm packages:
- https://www.npmjs.com/package/xstream

### I am not an evil charlatan
- [x] I will use my permissions within the esm-bundle Github organization to further the greater community's interests.

**Comment by joeldenning** [comment]
I've given you github and npm permissions. Welcome @rajasegar 

https://github.com/esm-bundle/xstream

https://www.npmjs.com/package/@esm-bundle/xstream
